# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B clean verify --file pom.xml -s $GITHUB_WORKSPACE/settings.xml -e -Dmaven.wagon.http.pool=false org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.links.homepage=https://github.com/joergi/basics -Dsonar.links.scm=https://github.com/joergi/basics -Dsonar.login=${{ secrets.SONARCLOUD }}
      env:
        MVN_AUTH_TOKEN: ${{ secrets.PACKAGES_READ_ONLY }}
        # Needed to get some information about the pull request, if any
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
